// angular-react-vue/EdgeSharp.React.Sample/reactapp/src/components/Home.js
import React from 'react';
import { useState, useEffect } from 'react';
import { actionClientGet } from '../services/ActionControllerClientService.js';

export default function Home() {

  const [sdkVersion, setSdkVersion] = useState('');
  const [runtimeVersion, setRuntimeVersion] = useState('');

  const getInfoCallback = (res) => {
    setSdkVersion(res.sdk);
    setRuntimeVersion(res.runtime);
  };

  const getInfo = () => {
    actionClientGet('http://edgesharp.com/info', getInfoCallback);
  };

  useEffect(() => {
    getInfo();
  }, []);

  return (
    <div>
      <div className="text-center mt-5">
        <h1 className="display-3">EdgeSharp</h1>
        <p className="lead text-muted">Build .NET Win32/WinForms/WPF WebView2 HTML5 Desktop Apps</p>

        <div className="row">
          <div className="col-sm-3"></div>
          <div className="col-sm-6">
            <table className="table table-sm">
              <tbody>
                <tr>
                  <td><small className="text-muted">WebView2 SDK Version: {sdkVersion}</small></td>
                </tr>
                <tr>
                  <td><small className="text-muted text-primary">WebView2 Runtime Version: {runtimeVersion}</small></td>
                </tr>
              </tbody>
            </table>
          </div>
          <div className="col-sm-3"></div>
        </div>
        <div className="text-center">
            <a href="https://github.com/edgesharp/EdgeSharp" className="btn btn-primary btn-sm" role="button" style={{margin: '5px'}}>more info</a>
        </div>
      </div>
  </div>
  );
}

// angular-react-vue/EdgeSharp.Vue.Sample/vueapp/src/components/Home.vue
<template>
 <div>
    <div class="text-center mt-5">
      <h1 class="display-3">EdgeSharp</h1>
      <p class="lead text-muted">Build .NET Win32/WinForms/WPF WebView2 HTML5 Desktop Apps</p>

      <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
          <table class="table table-sm">
            <tbody>
              <tr>
                <td><small class="text-muted">WebView2 SDK Version: {{sdkVersion}}</small></td>
              </tr>
              <tr>
                <td><small class="text-muted">WebView2 Runtime Version: {{runtimeVersion}}</small></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-sm-3"></div>
      </div>
      <div class="text-center">
          <a href="https://github.com/edgesharp/EdgeSharp" class="btn btn-primary btn-sm" role="button" style='margin: 5px;'>more info</a>
      </div>
    </div>
</div>
</template>


<script>
var actionClient = require('../services/ActionControllerClient');

export default {
  data(){
    return{
      sdkVersion: '',
      runtimeVersion: ''
    }
  },
  methods: {
		getInfoCallback (response) {
            this.sdkVersion = response.sdk;
            this.runtimeVersion = response.runtime;
		}
	},
  mounted(){
    actionClient.get('http://edgesharp.com/info', this.getInfoCallback);
  }
}
</script>
