// angular-react-vue/EdgeSharp.Vue.Sample/vueapp/src/components/Home.vue
<template>
 <div>
    <div class="text-center mt-5">
      <h1 class="display-3">EdgeSharp</h1>
      <p class="lead text-muted">Build .NET Win32/WinForms/WPF WebView2 HTML5 Desktop Apps</p>

      <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
          <table class="table table-sm">
            <tbody>
              <tr>
                <td><small class="text-muted">WebView2 SDK Version: {{sdkVersion}}</small></td>
              </tr>
              <tr>
                <td><small class="text-muted">WebView2 Runtime Version: {{runtimeVersion}}</small></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-sm-3"></div>
      </div>
      <div class="text-center">
          <a href="https://github.com/edgesharp/EdgeSharp" class="btn btn-primary btn-sm" role="button" style='margin: 5px;'>more info</a>
      </div>
    </div>
</div>
</template>


<script>
var actionClient = require('../services/ActionControllerClient');

export default {
  data(){
    return{
      sdkVersion: '',
      runtimeVersion: ''
    }
  },
  methods: {
		getInfoCallback (response) {
            this.sdkVersion = response.sdk;
            this.runtimeVersion = response.runtime;
		}
	},
  mounted(){
    actionClient.get('http://edgesharp.com/info', this.getInfoCallback);
  }
}
</script>

// angular-react-vue/EdgeSharp.Angular.Sample/angularapp/src/app/components/home/home.component.ts
import { Component, OnInit, NgZone } from '@angular/core';
import { ActionClientService } from '../../services/action.controller.client.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  _sdkVersion: string = '';
  _runtimeVersion: string = '';

  constructor(private _actionClientService: ActionClientService,
             private _zone: NgZone) { 

  }

  public reload() {
    this._actionClientService.execute('http://edgesharp.com/reload');
    return false;
  }

  ngOnInit(): void {
    this._actionClientService.get('http://edgesharp.com/info',  (data: any) => {
      this._zone.run(
          () => {
            this._sdkVersion = data.sdk;
            this._runtimeVersion = data.runtime;
          })
    });
  }
}

<div>
    <div class="text-center mt-5">
      <h1 class="display-3">EdgeSharp</h1>
      <p class="lead text-muted">Build .NET Win32/WinForms/WPF WebView2 HTML5 Desktop Apps</p>

      <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
          <table class="table table-sm">
            <tbody>
              <tr>
                <td><small class="text-muted">WebView2 SDK Version: {{_sdkVersion}}</small></td>
              </tr>
              <tr>
                <td><small class="text-muted">WebView2 Runtime Version: {{_runtimeVersion}}</small></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-sm-3"></div>
      </div>
      <div class="text-center">
          <a href="https://github.com/edgesharp/EdgeSharp" class="btn btn-primary btn-sm" role="button" style='margin: 5px;'>more info</a>
      </div>
    </div>
</div>
